project_id = "dlmijahsuhnrtnvjhazd"

[functions.generate-faqs]
verify_jwt = false

[functions.analyze-faq-relevance]
verify_jwt = false

[functions.regenerate-faq]
verify_jwt = false

[functions.parse-sitemap]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
